### PR TITLE
add orcid; style code; remove spelling errors

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Btw, one thing I noticed when I cloned the repo was that the size of the folder is 123MB! 

Do you know why that might be?

### CODE REVIEW

**Comment by bbolker** [comment]
I'm sorry to be a pain about this, but I would strongly prefer at least the code style changes to be in a separate commit.  (What code style did you use, and how did you execute it [e.g. editor, `styler` package, ...)

**Comment by bbolker** [comment]
I suspect that the large size of the repo has to do with the stored fitted-modelobjects that I use for testing. The fitted-model objects produced by Stan-based methods (`rstanarm`, `brms`, etc.) are very large; it took me several tries to figure out how to minimize their storage space, and it's quite possible that some of the unsuccessful attempts are stored in the repo history.

**Comment by IndrajeetPatil** [comment]
> I'm sorry to be a pain about this, but I would strongly prefer at least the code style changes to be in a separate commit. (What code style did you use, and how did you execute it [e.g. editor, styler package, ...)

I am using `tidyverse` style guide, which is what `broom` uses as well so it will good to be consistent with it. I will try to make a separate PR soon.

**Comment by bbolker** [comment]
thanks!  Did you use `styler`?

**Comment by IndrajeetPatil** [comment]
Yes, `styler::style_pkg()`

**Pull request closed without merging**
