### PR TITLE
Reduce dependencies: TMB, coda, cubelyr

### PR DESCRIPTION
**Pull request by vincentarelbundock**
This PR does 5 things:

* Move `TMB` to Suggests
* Move `coda` to Suggests
* Remove dependency to `cubelyr`. This was used only once, so I wrote a few lines of code to "flatten" a data cube.
* Ordered the dependencies in alphabetical order in DESCRIPTION
* Add a function called `assert_dependency` which is called before any functions from `TMB` or `coda` are called. When the packages are not installed (should never happen in practice if the user estimated the model themselves), `assert_dependency` stops execution and asks the user to install the relevant package.

In my initial comment https://github.com/bbolker/broom.mixed/issues/102 I suggested removing `nlme` and moving from `broom` to `generics`. However, this turned out to be trickier than I expected, so I decided to stop here for now.

Let me know what you think.

### CODE REVIEW

**Comment by bbolker** [comment]
I'm sorry not to have commented on this quicker, I meant to (but I have actually been feeling a little unwell/feverish - wondering if it can possibly be COVID-19, I have very few close contacts ...)

It makes sense to me to move `TMB` to `Suggests`, but *not* `coda`: the distinction is that `TMB` is *only* needed for `TMB` models (and indirectly for `glmmTMB` models, although that's handled by `glmmTMB`), whereas `coda` is a *generic* tool for post-processing MCMC output.  Also, `coda` has no dependencies of its own other than `lattice` (a recommended package), so it adds very little overhead.

I absolutely agree with streamlining, but there is also some small downside to cluttering the code with `assert_dependency()` statements everywhere, so this is one place where I think it's not worth it.

I might have said the same thing about `nlme` (in addition to its `nlme`-specific uses, it is also the source of the `VarCorr`, `fixef`, `ranef`, which are generics that are used by almost all downstream packages.  If these were in `generics` it would make sense to import them from there instead, but I don't think they are (I searched the GH repo - I might have missed them since GH search is so terrible ...)

On the other hand, all of your other suggestions/changes (get rid of `cubelyr`, eventually replace `broom` with `generics` ...) seem very sensible.

**Comment by vincentarelbundock** [comment]
The main reason to kick `coda` out would be for someone who uses `lme4` and has no use for mcmc. Since that's likely on a non-trivial part of the user base, I thought it justified moving it Suggests. 

But it's not a big deal; I'm happy to do whatever you feel more confortable with. This last commit brings `coda` back in by deleting 6 `assert_dependency` calls.

The issue with `broom`->`generics` is that `broom.mixed` uses `augment_columns` a few times. I haven't spent enough time with the internals to figure out if there's an easy substitute.

**Comment by bbolker** [comment]
I'm not sure I had a really good reason for using `augment_columns` except that it was there in `broom`. We could just copy it, although that also feels like bad practice. `broom` is slightly heavier in terms of requirements than the other packages you're trying to trim (because it makes unrestricted use of tidyverse machinery, so it needs `backports`, `glue`, `ellipsis`, `rlang` (in addition to `generics`, which would be a one-for-one swap for `broom` itself ...)

**Comment by bbolker** [comment]
PS let me know how you want your name added to the 'ctb' list in DESCRIPTION (real name, Github name? ORCID?) - or submit another PR for that ...

**Comment by vincentarelbundock** [comment]
Oh, this is what I use usually, but honestly, I don't think it's necessary for such a small thing.

```r
Authors@R: person("Vincent", "Arel-Bundock", 
                  email = "vincent.arel-bundock@umontreal.ca", 
                  role = c("aut", "cre"),
                  comment = c(ORCID = "0000-0003-2042-7063"))
```

**Pull request merged**
